using Daedalus.Rotation.Common;
using Daedalus.Rotation.Common.Helpers;
using Daedalus.Rotation.IrisCore.Helpers;
using Daedalus.Services.Party;
using Daedalus.Services.Training;
using static Daedalus.Data.PCTActions;

namespace Daedalus.Rotation.IrisCore.Context;

/// <summary>
/// Pictomancer-specific rotation context.
/// Extends caster DPS context with PCT gauge, canvas, and muse state.
/// </summary>
public interface IIrisContext : ICasterDpsRotationContext
{
    #region Palette Gauge

    /// <summary>
    /// Palette Gauge value (0-100).
    /// Filled by completing combos.
    /// </summary>
    int PaletteGauge { get; }

    /// <summary>
    /// Whether Subtractive Palette can be used (gauge >= 50).
    /// </summary>
    bool CanUseSubtractivePalette { get; }

    #endregion

    #region Paint Stacks

    /// <summary>
    /// White Paint stacks (0-5).
    /// Generated by completing combos.
    /// </summary>
    int WhitePaint { get; }

    /// <summary>
    /// Whether White Paint is available.
    /// </summary>
    bool HasWhitePaint { get; }

    /// <summary>
    /// Whether Black Paint is available (0-1).
    /// Generated via Subtractive Palette during Monochrome Tones.
    /// </summary>
    bool HasBlackPaint { get; }

    #endregion

    #region Canvas State

    /// <summary>
    /// Whether a creature is painted on canvas.
    /// </summary>
    bool HasCreatureCanvas { get; }

    /// <summary>
    /// The type of creature painted on canvas.
    /// </summary>
    CreatureMotifType CreatureMotifType { get; }

    /// <summary>
    /// Whether a weapon (hammer) is painted on canvas.
    /// </summary>
    bool HasWeaponCanvas { get; }

    /// <summary>
    /// Whether a landscape (starry sky) is painted on canvas.
    /// </summary>
    bool HasLandscapeCanvas { get; }

    #endregion

    #region Muse State

    /// <summary>
    /// Living Muse charges (2 max).
    /// </summary>
    int LivingMuseCharges { get; }

    /// <summary>
    /// Whether Living Muse is ready.
    /// </summary>
    bool LivingMuseReady { get; }

    /// <summary>
    /// Whether Striking Muse is ready.
    /// </summary>
    bool StrikingMuseReady { get; }

    /// <summary>
    /// Whether Starry Muse is ready (2-min cooldown).
    /// </summary>
    bool StarryMuseReady { get; }

    #endregion

    #region Portrait State

    /// <summary>
    /// Whether Mog of the Ages is ready (after 2 Living Muses).
    /// </summary>
    bool MogReady { get; }

    /// <summary>
    /// Whether Retribution of the Madeen is ready (after 4 Living Muses).
    /// </summary>
    bool MadeenReady { get; }

    #endregion

    #region Hammer Combo State

    /// <summary>
    /// Whether currently in the Hammer combo.
    /// </summary>
    bool IsInHammerCombo { get; }

    /// <summary>
    /// Current step in the Hammer combo (0-2).
    /// </summary>
    int HammerComboStep { get; }

    /// <summary>
    /// Number of Hammer Time stacks remaining.
    /// </summary>
    int HammerTimeStacks { get; }

    #endregion

    #region Base Combo State

    /// <summary>
    /// Current step in the base/subtractive combo (0-2).
    /// </summary>
    int BaseComboStep { get; }

    /// <summary>
    /// Whether currently in subtractive combo mode.
    /// </summary>
    bool IsInSubtractiveCombo { get; }

    #endregion

    #region Buff State

    /// <summary>
    /// Whether Starry Muse buff is active (party damage buff).
    /// </summary>
    bool HasStarryMuse { get; }

    /// <summary>
    /// Remaining duration of Starry Muse buff.
    /// </summary>
    float StarryMuseRemaining { get; }

    /// <summary>
    /// Whether Hyperphantasia is active (enhanced state during Starry Muse).
    /// </summary>
    bool HasHyperphantasia { get; }

    /// <summary>
    /// Number of Hyperphantasia stacks.
    /// </summary>
    int HyperphantasiaStacks { get; }

    /// <summary>
    /// Whether Inspiration is active (reduced motif cast time).
    /// </summary>
    bool HasInspiration { get; }

    /// <summary>
    /// Whether Subtractive Spectrum is active (enhanced subtractive spells).
    /// </summary>
    bool HasSubtractiveSpectrum { get; }

    /// <summary>
    /// Whether Starstruck is active (Star Prism ready).
    /// </summary>
    bool HasStarstruck { get; }

    /// <summary>
    /// Whether Rainbow Bright is active (instant Rainbow Drip).
    /// </summary>
    bool HasRainbowBright { get; }

    /// <summary>
    /// Whether Hammer Time is active (hammer combo available).
    /// </summary>
    bool HasHammerTime { get; }

    /// <summary>
    /// Whether Subtractive Palette buff is active.
    /// </summary>
    bool HasSubtractivePalette { get; }

    /// <summary>
    /// Remaining duration of Subtractive Palette buff.
    /// </summary>
    float SubtractivePaletteRemaining { get; }

    /// <summary>
    /// Whether Monochrome Tones is active (Black Paint mode).
    /// </summary>
    bool HasMonochromeTones { get; }

    #endregion

    #region Cooldown State

    /// <summary>
    /// Whether Subtractive Palette ability is ready.
    /// </summary>
    bool SubtractivePaletteReady { get; }

    /// <summary>
    /// Whether Tempera Coat is ready.
    /// </summary>
    bool TemperaCoatReady { get; }

    /// <summary>
    /// Whether Tempera Grassa is ready.
    /// </summary>
    bool TemperaGrassaReady { get; }

    /// <summary>
    /// Whether Smudge is ready.
    /// </summary>
    bool SmudgeReady { get; }

    /// <summary>
    /// Whether Swiftcast is ready.
    /// </summary>
    bool SwiftcastReady { get; }

    /// <summary>
    /// Whether Lucid Dreaming is ready.
    /// </summary>
    bool LucidDreamingReady { get; }

    #endregion

    #region Helpers

    /// <summary>
    /// Status helper for checking buffs and debuffs.
    /// </summary>
    IrisStatusHelper StatusHelper { get; }

    /// <summary>
    /// Party helper for party member operations.
    /// </summary>
    CasterPartyHelper PartyHelper { get; }

    /// <summary>
    /// Debug state for UI display.
    /// </summary>
    IrisDebugState Debug { get; }

    #endregion

    #region Utility Properties

    /// <summary>
    /// Whether we should use AoE rotation (3+ enemies).
    /// </summary>
    bool ShouldUseAoe { get; }

    /// <summary>
    /// Number of nearby enemies in range.
    /// </summary>
    int NearbyEnemyCount { get; }

    /// <summary>
    /// Whether we're in a burst window (Starry Muse active).
    /// </summary>
    bool IsInBurstWindow { get; }

    /// <summary>
    /// Whether we can paint a motif (not in combat or downtime).
    /// </summary>
    bool CanPaintMotif { get; }

    /// <summary>
    /// Whether we need to paint a creature motif.
    /// </summary>
    bool NeedsCreatureMotif { get; }

    /// <summary>
    /// Whether we need to paint a weapon motif.
    /// </summary>
    bool NeedsWeaponMotif { get; }

    /// <summary>
    /// Whether we need to paint a landscape motif.
    /// </summary>
    bool NeedsLandscapeMotif { get; }

    #endregion

    #region Party Coordination

    /// <summary>
    /// Service for coordinating raid buffs with other Daedalus instances.
    /// Null if party coordination is disabled or unavailable.
    /// </summary>
    IPartyCoordinationService? PartyCoordinationService { get; }

    #endregion

    #region Training

    /// <summary>
    /// Training service for decision explanations.
    /// </summary>
    ITrainingService? TrainingService { get; }

    #endregion
}
